"""empty message

Revision ID: 251b92933f5a
Revises: 905e16141358
Create Date: 2020-09-05 13:10:43.447966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251b92933f5a'
down_revision = '905e16141358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('completed', sa.Boolean(), nullable=True))
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('todolists', 'completed')
    # ### end Alembic commands ###
